### ISSUE TITLE
Integration with vim-airline

### ISSUE THREAD

**Issue by stsewd** [soywod/vim-keepeye#2]
Hi, thanks for this amazing plugin.

I notice that when changing buffers the message disappears. Normally this shouldn't be a problem, but I change buffers so fast (I have a mapping for this) that sometimes the message is lost.

Is this a vim limitation or can be fixed? (I use Neovim by the way)

**Comment by stsewd** [comment]
Mmm, I think this is because the plugin is incompatible with airline, without airline it works.

**Comment by soywod** [comment]
Yes indeed, it's because of airline. In fact airline re-write often this statusbar, which makes my plugin disappearing. The options I see : 
 - Integrate this plugin inside airline (instead of replacing all the statusbar)
 - Once the time reached, put this message every 20sec till we leave Vim

What do you think ?

**Comment by stsewd** [comment]
I think a integration with airline is what we need, but only do this if airline is present, otherwise just use the current behavior.

**Comment by soywod** [comment]
I think too, I'll poke sth soon about this

**Comment by soywod** [comment]
Feature added https://github.com/soywod/vim-keepeye/commit/15a937744ce1b6e5ed17d10e1ba51ae1df5de864 :tada:

**Comment by stsewd** [comment]
@soywod thanks!
